config/routes.rb
Rails.application.routes.draw do
  root "restaurants#index"
  devise_for :users
  resources :restaurants do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, length: { minimum: 3 }, uniqueness: true

  def average_rating
    return 'N/A' if reviews.none?
    reviews.inject(0) {|memo, review| memo + review.rating }/reviews.count
  end
end

app/models/review.rb
class Review < ApplicationRecord
  validates :rating, inclusion: (1..5)
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :restaurants
         has_many :reviews
         has_many :reviewed_restaurants, through: :reviews, source: :restaurants


         def has_reviewed?(restaurants)
           reviewed_restaurants.include? restaurant
         end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to '/restaurants'
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to '/restaurants'
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = 'Restaurant deleted successfully'
    redirect_to '/restaurants'
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :description)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @restaurant.reviews.create(review_params)
    redirect_to '/restaurants'
  end

  private

  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodiesAdda</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice %>
    <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
    <%= link_to "Sign in", new_user_session_path %>
    <%= link_to "Sign up", new_user_registration_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<%= form_for @restaurant do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :description%>
<%= f.text_field :description %>
<%= f.submit 'Update Restaurant' %>
<% end %>

app/views/restaurants/index.html.erb
<% if @restaurants.any? %>
<% @restaurants.each do |restaurant| %>
<h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
<h2><%= restaurant.description %>
    <h2><%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %></h2>
    <h2><%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete%>
    </h2>
    <h2><%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant) %>
    </h2>
    <h2>Average rating: <%= restaurant.average_rating %></h2>
    <% if restaurant.reviews.any? %>
    <% restaurant.reviews.each do |review| %>
    <%= review.thoughts %>
    <%= review.rating %>
    <% end %>
    <% end %>
    <br>
    <% end %>
<% else %>
    <h1>No restaurants yet</h1>
    <br>
    <% end %>

    <%= link_to "Add a restaurant", new_restaurant_url %>

app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
<section id="errors">
    <h2>
        <%= pluralize(@restaurant.errors.count, "error") %>
        prohibited this restaurant from being saved:
    </h2>
    <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</section>
<% end %>
<%= form_for @restaurant do |f| %>
<%= f.label :name %>
<%= f.text_field :name%>
<%= f.submit 'Create Restaurant'%>
<% end %>

app/views/restaurants/show.html.erb
<p> <%= @restaurant.name %> </p> :
<p> <%= @restaurant.description %> </p>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
<%= f.label :thoughts %>
<%= f.text_area :thoughts %>
<%= f.label :rating %>
<%= f.select :rating, (1..5) %>
<%= f.submit 'Leave Review' %>
<% end %>